name: BuildMeshLab

on:
  [push, pull_request]

env:
  QT_VERSION: 5.15.2
  MAC_CERT: ${{secrets.MACOS_CERT_ID}}
  WIN_CERT: ${{secrets.WIN_CERTIFICATE}}

jobs:
  meshlab_build:
    uses: alemuntoni/cpp-build-deploy/.github/workflows/build.yml@main