name: BuildMeshLab

on:
  [push, pull_request]

env:
  QT_VERSION: 5.15.2

jobs:
  meshlab_build:
    name: Build MeshLab
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04', 'macos-latest', 'macos-14', 'windows-latest']
        precision: [single_precision, double_precision]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup env variables
      id: envs
      shell: bash
      run: |
        ARCH=$(uname -m)

        build_options="--nightly --ccache"
        
        if [ "${{matrix.os}}" == "macos-14" ]; then
          echo "setup_env_options=" >> $GITHUB_OUTPUT
          build_options="$build_options --use_brew_qt"
        else
          echo "setup_env_options=--dont_install_qt" >> $GITHUB_OUTPUT
        fi

        if [ "${{matrix.precision}}" == "double_precision" ]; then
          echo "artifact_suffix=_double_$ARCH" >> $GITHUB_OUTPUT
          build_options="$build_options --double_precision"
        else
          echo "artifact_suffix=_$ARCH" >> $GITHUB_OUTPUT
        fi

        echo "build_options=$build_options" >> $GITHUB_OUTPUT
    - name: Setup Environment
      uses: ./.github/actions/0_setup
      with:
        script-path: scripts/${{ runner.os }}/0_setup_env.sh
        script-arguments: ${{steps.envs.outputs.setup_env_options}}
        use-jurpel-qt-action: ${{matrix.os != 'macos-14'}}
    - name: Build
      uses: ./.github/actions/1_build
      with:
        script-path: scripts/${{ runner.os }}/1_build.sh
        script-arguments: ${{steps.envs.outputs.build_options}}
        ccache-key: ${{matrix.precision}}
        cache-path: src/external/downloads/*
        cache-key: external-libraries
    - name: Deploy
      uses: ./.github/actions/2_deploy
      with:
        use-brew-qt: ${{matrix.os == 'macos-14'}}
        mac-certificate: ${{ secrets.MACOS_CERTIFICATE }}
        mac-certificate-id: ${{ secrets.MACOS_CERT_ID }}
        mac-certificate-pssw: ${{ secrets.MACOS_CERTIFICATE_PSSW }}
        win-certificate: ${{ secrets.WIN_CERTIFICATE }}
        win-certificate-pssw: ${{ secrets.WIN_CERTIFICATE_PSSW }}
    - name: Upload MeshLab Portable
      uses: actions/upload-artifact@v4
      with:
        name: MeshLab_${{ runner.os }}_portable${{steps.envs.outputs.artifact_suffix}}
        path: install/
    - name: Upload MeshLab Packages
      uses: actions/upload-artifact@v4
      with:
        name: MeshLab_${{ runner.os }}_packages${{steps.envs.outputs.artifact_suffix}}
        path: packages/MeshLab*